// KOLO - Localization translations
const translations = {
  en: {
    // Landing
    loginToKolo: "Log in to KOLO",
    heroHeadline: "Never Miss a Follow-Up Again!",
    heroSubheadline: "Close more deals. Automatically.",
    feature1Title: "Today's Follow-Ups",
    feature1Desc: "Know exactly who to contact today.",
    feature2Title: "Active Prospects",
    feature2Desc: "Every buyer and seller to close.",
    feature3Title: "Smart Reminders",
    feature3Desc: "Automatic reminders based on your tasks and real activity.",
    madeBy: "Made by independent real estate agents for independent real estate agents",
    startButton: "Start",
    cancelAnytime: "Cancel anytime",
    perMonth: "/month",
    
    // Login
    back: "Back",
    welcomeBack: "Good to see you again!",
    email: "Email",
    password: "Password",
    signIn: "Sign In",
    or: "or",
    continueWithGoogle: "Continue with Google",
    
    // Subscribe
    subscribeToKolo: "Subscribe to KOLO",
    startClosingDeals: "Start closing more deals today",
    monthlySubscription: "Monthly Subscription",
    choosePaymentMethod: "Choose Payment Method",
    creditDebitCard: "Credit / Debit Card",
    applePay: "Apple Pay",
    unlimitedLeads: "Unlimited leads and tasks",
    
    // Create Account
    createYourAccount: "Create Your Account",
    chooseSignUp: "Choose how you want to sign up",
    orWithEmail: "or with email",
    confirmPassword: "Confirm Password",
    createAccount: "Create Account",
    termsLine: "By creating an account, you agree to our Terms of Service and Privacy Policy.",
    
    // App - Today
    today: "Today",
    myProfile: "My Profile",
    allCaughtUp: "All caught up!",
    noPendingTask: "No pending task",
    taskCompleted: "Task completed!",
    taskError: "Failed to update task",
    autoGenerated: "Auto-generated",
    
    // App - Prospects
    prospects: "Prospects",
    addProspect: "Add Prospect",
    noProspects: "No prospects yet",
    addFirstProspect: "Add your first prospect to get started",
    
    // App - Prospect Detail
    nextScheduledTask: "Next Scheduled Task",
    tasks: "TASKS",
    addTask: "Add Task",
    taskTitle: "Task title",
    taskCreated: "Task created!",
    noTasks: "No tasks yet",
    notes: "NOTES",
    statusUpdated: "Status updated!",
    updateError: "Failed to update",
    
    // App - Settings
    settings: "Settings",
    profile: "PROFILE",
    billingPayment: "BILLING & PAYMENT",
    editPaymentMethod: "Edit payment method",
    changeCard: "Change bank card",
    billingAddress: "Billing address",
    changeEmail: "Change email",
    about: "ABOUT",
    version: "Version",
    logout: "Logout",
    
    // New Prospect
    cancel: "Cancel",
    newProspect: "New Prospect",
    save: "Save",
    fullName: "Full name *",
    phone: "Phone *",
    emailRequired: "Email *",
    source: "Source",
    manual: "Manual",
    whatsapp: "WhatsApp",
    emailSource: "Email",
    status: "Status",
    statusNew: "New",
    statusInProgress: "In Progress",
    statusClosed: "Closed",
    statusLost: "Lost",
    addNotes: "Add notes (optional)",
    
    // Payment
    processing: "Processing...",
    paymentSuccess: "Payment successful!",
    paymentFailed: "Payment failed. Please try again.",
    
    // Auth
    subscriptionRequired: "Active subscription required",
    pleaseSubscribe: "Please subscribe to access the app",
    goToSubscribe: "Go to Subscribe",
  },
  fr: {
    // Landing
    loginToKolo: "Se connecter à KOLO",
    heroHeadline: "Ne Manquez Plus Jamais une Relance !",
    heroSubheadline: "Concluez plus d'affaires. Automatiquement.",
    feature1Title: "Relances du Jour",
    feature1Desc: "Sachez exactement qui contacter aujourd'hui.",
    feature2Title: "Prospects Actifs",
    feature2Desc: "Chaque acheteur et vendeur à conclure.",
    feature3Title: "Relances Intelligentes",
    feature3Desc: "Rappels basés sur vos tâches et votre activité réelle.",
    madeBy: "Fait par des indépendants de l'immobilier pour des indépendants de l'immobilier",
    startButton: "Commencer",
    cancelAnytime: "Annulez à tout moment",
    perMonth: "/mois",
    
    // Login
    back: "Retour",
    welcomeBack: "C'est bon de vous revoir !",
    email: "Email",
    password: "Mot de passe",
    signIn: "Se connecter",
    or: "ou",
    continueWithGoogle: "Continuer avec Google",
    
    // Subscribe
    subscribeToKolo: "S'abonner à KOLO",
    startClosingDeals: "Commencez à conclure plus d'affaires aujourd'hui",
    monthlySubscription: "Abonnement Mensuel",
    choosePaymentMethod: "Choisir le Mode de Paiement",
    creditDebitCard: "Carte de Crédit / Débit",
    applePay: "Apple Pay",
    unlimitedLeads: "Prospects et tâches illimités",
    
    // Create Account
    createYourAccount: "Créez Votre Compte",
    chooseSignUp: "Choisissez comment vous inscrire",
    orWithEmail: "ou avec email",
    confirmPassword: "Confirmer le mot de passe",
    createAccount: "Créer un compte",
    termsLine: "En créant un compte, vous acceptez nos Conditions d'utilisation et notre Politique de confidentialité.",
    
    // App - Today
    today: "Aujourd'hui",
    myProfile: "Mon Profil",
    allCaughtUp: "Tout est à jour !",
    noPendingTask: "Aucune tâche en attente",
    taskCompleted: "Tâche terminée !",
    taskError: "Erreur lors de la mise à jour",
    autoGenerated: "Générée automatiquement",
    
    // App - Prospects
    prospects: "Prospects",
    addProspect: "Ajouter un Prospect",
    noProspects: "Aucun prospect",
    addFirstProspect: "Ajoutez votre premier prospect pour commencer",
    
    // App - Prospect Detail
    nextScheduledTask: "Prochaine Tâche Programmée",
    tasks: "TÂCHES",
    addTask: "Ajouter une tâche",
    taskTitle: "Titre de la tâche",
    taskCreated: "Tâche créée !",
    noTasks: "Aucune tâche",
    notes: "NOTES",
    statusUpdated: "Statut mis à jour !",
    updateError: "Erreur lors de la mise à jour",
    
    // App - Settings
    settings: "Paramètres",
    profile: "PROFIL",
    billingPayment: "FACTURATION ET PAIEMENT",
    editPaymentMethod: "Modifier le moyen de paiement",
    changeCard: "Changer de carte bancaire",
    billingAddress: "Adresse de facturation",
    changeEmail: "Modifier l'email",
    about: "À PROPOS",
    version: "Version",
    logout: "Déconnexion",
    
    // New Prospect
    cancel: "Annuler",
    newProspect: "Nouveau Prospect",
    save: "Enregistrer",
    fullName: "Nom complet *",
    phone: "Téléphone *",
    emailRequired: "Email *",
    source: "Source",
    manual: "Manuel",
    whatsapp: "WhatsApp",
    emailSource: "Email",
    status: "Statut",
    statusNew: "Nouveau",
    statusInProgress: "En cours",
    statusClosed: "Conclu",
    statusLost: "Perdu",
    addNotes: "Ajouter des notes (optionnel)",
    
    // Payment
    processing: "Traitement...",
    paymentSuccess: "Paiement réussi !",
    paymentFailed: "Échec du paiement. Veuillez réessayer.",
    
    // Auth
    subscriptionRequired: "Abonnement actif requis",
    pleaseSubscribe: "Veuillez vous abonner pour accéder à l'application",
    goToSubscribe: "S'abonner",
  }
};

export default translations;
